import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
import { Banner, OurPromis, ContactUsForm } from '@/components/pages'
export default function Home() {


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${inter.className}`}>


                <div className='row'>
                    <div className='col-12'>
                        <Banner title={<span>About RVSB Technologies</span>} description="We operate with high standards of refinement and urbanity to serve our clients. Our client servicing constitutes devising and execution of a project however, we do not limit ourselves when it comes to offering a flexible solution. We also try to understand the problems faced by our clients and only after we have provided the absolute best possible solution to the problem do we consider it a successful venture." bannerImage='/why-us.png' />

                        <ContactUsForm />

                    </div>
                </div>


            </main>
        </>
    )
}
