import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
import { Banner, AboutCompany, OurServicesCard, HaveQue,OurCustomer } from '@/components/pages'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>


        <div className='row'>
          <div className='col-12'>
          <Banner title={<span>Next generation <br/> Software and Technology solutions</span>} description="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting," bannerImage='/why-us.png'/>
            <AboutCompany />
            <OurServicesCard />
            <HaveQue />
            <OurCustomer/>
          </div>
        </div>


      </main>
    </>
  )
}
